nami = pointer_ref

CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98

SRC = main.cpp HumanA.cpp HumanB.cpp Weapon.cpp
OBJ = $(SRC:.cpp=.o)

all:		$(nami)

$(nami):	$(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(nami)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(nami)

re: fclean all
